name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history and metadata
      run: |
        git fetch --prune --unshallow
        git checkout -b pr
        git branch -f main origin/main

    - name: Install clang-format
      run: |
        sudo apt-get update -q
        sudo apt-get install clang-format-10

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install wpiformat
      run: pip3 install wpiformat

    - name: Run wpiformat
      run: wpiformat -clang 10

    - name: Verify wpiformat made no changes
      run: git --no-pager diff --exit-code HEAD
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history and metadata
        run: |
          git fetch --prune --unshallow
          git checkout -b pr
          git branch -f main origin/main
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install clang-format and clang-tidy
        run: sudo apt-get update -q && sudo apt-get install -y clang-format-10 clang-tidy-10
      - name: Install wpiformat
        run: pip3 install wpiformat
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create compile_commands.json
        run: ./gradlew generateCompileCommands -Ptoolchain-optional-roboRio
      - name: Run clang-tidy
        run: wpiformat -clang 10 -no-format -tidy-all -compile-commands=build/compile_commands/linuxx86-64
  build-athena:
    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2021-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile robot code for Athena
      run: ./gradlew buildAthena
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            build-options: "-Ponlylinuxx86-64"
          - os: windows-latest
            name: windows
            build-options: "-Ponlywindowsx86-64"
          - os: macos-latest
            name: macos
            build-options: "-Ponlymacosx86-64"
    name: "test-${{ matrix.name }}"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run x86-64 unit tests
      run: ./gradlew test -Ptoolchain-optional-roboRio ${{ matrix.build-options }}
