# This is a basic workflow to build robot code.

name: CI

# Controls when the action will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Fetch all history and metadata
      run: git fetch --prune --unshallow

    - name: Install clang-format
      run: |
        sudo apt-get install clang-format-10

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install wpiformat
      run: pip3 install wpiformat

    - name: Run wpiformat
      run: |
        git checkout -b pr
        git checkout master
        git checkout pr
        wpiformat -clang 10

    # Ensure formatter made no changes
    - name: Check wpiformat output
      run: git --no-pager diff --exit-code HEAD
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2020-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile robot code for Athena
      run: ./gradlew frcUserProgramLinuxathenaReleaseExecutable
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2020-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run x86-64 unit tests
      run: ./gradlew runFrcUserProgramTestLinuxx86-64ReleaseGoogleTestExe
